spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect